AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gracies-eats-backend

  Sample SAM Template for gracies-eats-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GraciesEatsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Timeout: 10
      Events:
        GetAllUsers:
          Type: Api 
          Properties:
            Path: /users
            Method: get
        GetUser:
          Type: Api 
          Properties:
            Path: /users/{user_name}
            Method: get
        CreateUser:
          Type: Api 
          Properties:
            Path: /users
            Method: post
        UpdateUser:
          Type: Api 
          Properties:
            Path: /users/{user_name}
            Method: put
        GetUserRecipes:
          Type: Api
          Properties:
            Path: /users/{user_name}/recipes
            Method: get
        GetUserRecipe:
          Type: Api
          Properties:
            Path: /users/{user_name}/recipes/{recipe_id}
            Method: get
        CreateUserRecipe:
          Type: Api 
          Properties:
            Path: /users/{user_name}/recipes/{recipe_id}
            Method: post
        UpdateUserRecipe:
          Type: Api 
          Properties:
            Path: /users/{user_name}/recipes/{recipe_id}
            Method: put
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GraciesEatsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GraciesEatsFunction.Arn
  GraciesEatsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GraciesEatsFunctionRole.Arn
