version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::255499922602:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1RZYA5ARHFGIA"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::255499922602:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1T7TW9S1DXZ4K"
cloudformation_execution_role = "arn:aws:iam::255499922602:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1WYXMYU4J6U03"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1aqbwzsqzj9tu"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::255499922602:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-110KPHBE715NT"
cloudformation_execution_role = "arn:aws:iam::255499922602:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-145GHBWAYPUTC"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1wpoginfqanl3"
image_repository = ""
region = "us-east-1"
